base_url: http://127.0.0.1:8100/task1
api_key: z4fRNQW1xJidCuGO0l0G4eR97bkwPSdTbXSyMzeCRes=
store_dir: store
new_game_params:
  nb_players: 1
  map_side: 11
  nb_rounds: 10
  round_duration: 60
  cycles_per_round: 2
my_players:
  - number: 1
    command_line: "./team1.sh"
